apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: np-sourcegraph
resources:
  # Replace the version number to upgrade / downgrade
  - https://github.com/sourcegraph/deploy-sourcegraph/base?ref=bee/kustomize
components:
  - https://github.com/sourcegraph/kustomize/components/non-privileged
  - https://github.com/sourcegraph/kustomize/components/non-privileged-create-cluster
  - https://github.com/sourcegraph/kustomize/components/delete-cadvisor
  # Or to refer to the components locally:
  # - ../../components/non-privileged
  # - ../../components/non-privileged-create-cluster
