apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sourcegraph-production-overlay
resources:
  # Replace the version number to upgrade / downgrade
  - https://github.com/sourcegraph/deploy-sourcegraph/base?ref=kustomize.example
components:
  - https://github.com/sourcegraph/kustomize/components/serviceType/LoadBalancer
  - https://github.com/sourcegraph/kustomize/components/delete-cadvisor
  - https://github.com/sourcegraph/kustomize/components/non-privileged
  - https://github.com/sourcegraph/kustomize/components/non-privileged-create-cluster
  - https://github.com/sourcegraph/kustomize/components/delete-daemonset
  - https://github.com/sourcegraph/kustomize/components/delete-rolebinding
  - https://github.com/sourcegraph/kustomize/components/delete-default-ingress
  - https://github.com/sourcegraph/kustomize/components/storageclass-name

images:
- name: index.docker.io/sourcegraph/cadvisor
  newName: my.image.registry/sourcegraph/cadvisor
  newTag: replace.me.tag

configMapGenerator:
- name: environment-variables
  # update storage name inside the .sourcegraph_config.env file
  env: .sourcegraph_config.env
