apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: np-sourcegraph
resources:
  # Replace the version number to upgrade / downgrade
  - https://github.com/sourcegraph/deploy-sourcegraph/base?ref=kustomize.example
secretGenerator:
  - name: db-secrets
    envs:
      - .env.secret
