apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: environment-variables
  # A placeholder file
  env: patches/.sourcegraph_config.env
patchesJson6902:
  - target:
      kind: StatefulSet
      name: gitserver
      group: apps
      version: v1
    path: patches/replace-storageclass-name-sts.yaml
  - target:
      kind: StatefulSet
      name: grafana
      group: apps
      version: v1
    path: patches/replace-storageclass-name-sts.yaml
  - target:
      kind: StatefulSet
      name: indexed-search
      group: apps
      version: v1
    path: patches/replace-storageclass-name-sts.yaml
  - target:
      kind: PersistentVolumeClaim
      name: prometheus
      version: v1
    path: patches/replace-storageclass-name-pvc.yaml
  - target:
      kind: PersistentVolumeClaim
      name: pgsql
      version: v1
    path: patches/replace-storageclass-name-pvc.yaml
  - target:
      kind: PersistentVolumeClaim
      name: redis-cache
      version: v1
    path: patches/replace-storageclass-name-pvc.yaml
  - target:
      kind: PersistentVolumeClaim
      name: redis-store
      version: v1
    path: patches/replace-storageclass-name-pvc.yaml
  - target:
      kind: PersistentVolumeClaim
      name: codeintel-db
      version: v1
    path: patches/replace-storageclass-name-pvc.yaml
  - target:
      kind: PersistentVolumeClaim
      name: minio
      version: v1
    path: patches/replace-storageclass-name-pvc.yaml
  - target:
      kind: PersistentVolumeClaim
      name: codeinsights-db
      version: v1
    path: patches/replace-storageclass-name-pvc.yaml
configurations:
  - patches/storageclass-transformer.yaml
vars:
- name: DEPLOY_SOURCEGRAPH_STORAGECLASS_NAME
  objref:
    kind: ConfigMap
    name: environment-variables
    apiVersion: v1
  fieldref:
    fieldpath: data.DEPLOY_SOURCEGRAPH_STORAGECLASS_NAME