apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# update namespace value if needed
namespace: ns-sourcegraph
resources:
  # Replace the version number to upgrade / downgrade
  - https://github.com/sourcegraph/deploy-sourcegraph/base?ref=kustomize.example
components:
  - https://github.com/sourcegraph/kustomize/components/storageclass-name
  # - ../../components/storageclass-name
configMapGenerator:
- name: environment-variables
  behavior: replace
  # update storage name inside the .sourcegraph_config.env file
  env: .sourcegraph_config.env
