apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: ConfigMap
      name: newSecurityContext
      fieldPath: data.NEWRUNASUSER
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.template.spec.securityContext.runAsUser
          - spec.template.spec.containers.*.securityContext.runAsUser
          - spec.template.spec.initContainers.*.securityContext.runAsUser

  - source:
      kind: ConfigMap
      name: newSecurityContext
      fieldPath: data.NEWRUNASUSER
    targets:
      - select:
          kind: StatefulSet
        fieldPaths:
          - spec.template.spec.securityContext.runAsUser
          - spec.template.spec.containers.*.securityContext.runAsUser
          - spec.template.spec.initContainers.*.securityContext.runAsUser

  - source:
      kind: ConfigMap
      name: newSecurityContext
      fieldPath: data.NEWRUNASUSER
    targets:
      - select:
          kind: DaemonSet
        fieldPaths:
          - spec.template.spec.securityContext.runAsUser
          - spec.template.spec.containers.*.securityContext.runAsUser
          - spec.template.spec.initContainers.*.securityContext.runAsUser
