apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesStrategicMerge:
- |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      app.kubernetes.io/component: frontend
    name: sourcegraph-frontend
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: sourcegraph-frontend
  $patch: delete