apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-sourcegraph
resources:
  # Replace the version number to upgrade / downgrade
  - https://github.com/sourcegraph/deploy-sourcegraph/base?ref=v4.2.0
components:
  - https://github.com/sourcegraph/kustomize/components/storageclass-azure