apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# update namespace value if needed
namespace: ns-sourcegraph
resources:
  # Replace the version number to upgrade / downgrade
  - https://github.com/sourcegraph/deploy-sourcegraph/base?ref=v4.2.0
components:
  - https://github.com/sourcegraph/kustomize/components/storageclass
  # - ../../components/storageclass
configMapGenerator:
- name: environment-variables
  # update storage name inside the .storageclass.env file
  env: .storageclass.env
configurations:
  - storageclass-transformer.yaml
vars:
- name: DEPLOY_SOURCEGRAPH_STORAGECLASS_NAME
  objref:
    kind: ConfigMap
    name: environment-variables
    apiVersion: v1
  fieldref:
    fieldpath: data.DEPLOY_SOURCEGRAPH_STORAGECLASS_NAME