apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: sourcegraph-frontend
    name: sourcegraph-frontend
  spec:
    selector:
      app: sourcegraph-frontend
    $patch: replace
    type: LoadBalancer
